# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"
gem "jekyll"
gem 'faraday', '~> 2.7', '>= 2.7.11'

group :jekyll_plugins do
    gem "github-pages"
    gem "jekyll-feed"
    gem "jekyll-seo-tag"
    gem "jekyll-sitemap"
    gem "jekyll-paginate"
    gem "jekyll-toc"
    gem "jekyll-include-cache"
    gem "jekyll-avatar"
    gem "jekyll-mentions"
    gem "jekyll-remote-theme"
    gem "kramdown-parser-gfm"
end
